- name: "Install development packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      # Vim addons
      - vim-addon-manager
      - vim-airline
      - vim-fugitive
      - vim-syntastic
      - vim-youcompleteme
      # Utilities & applications
      - docker.io # Docker
      - libxml2-utils # xmllint
      - pandoc
      - yamllint
      # Development
      - bumpversion
      - make
      # Python
      - bandit
      - ipython3
      - mypy
      - pydocstyle
      - python3-flake8
      - python3-ipdb
      - python3-isort
      - python3-pip
      - tox
      - twine
      # LuaTaX
      - texlive-luatex
      - texlive-lang-czechslovak
      - texlive-latex-extra
