- name: "Install development packages"
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      # Vim addons
      - vim-addon-manager
      - vim-airline
      - vim-fugitive
      # Utilities & applications
      - direnv  # Custom environment variables per-directory
      - docker.io # Docker
      - docker-cli  # Docker CLIent
      - docker-compose
      - etherwake  # Wake on LAN
      - glab  # Gitlab CLIent
      - libxml2-utils # xmllint
      - pandoc
      - pspg  # PostgreSQL pager
      - thunderbird
      - yamllint
      # Development
      # - bumpversion  # Removed from testing
      - make
      # Python
      - ipython3
      - mypy
      - pydocstyle
      - python3-build
      - python3-ipdb
      - python3-pip
      - tox
      - twine
      # LuaTaX
      - texlive-extra-utils  # pdfjam
      - texlive-luatex
      - texlive-lang-czechslovak
      - texlive-latex-extra

- name: "Install pipx packages"
  community.general.pipx:
    name: "{{ item }}"
    state: "install"
  loop:
    - "bump-my-version"
    - "tox"
    - "twine"
