#!/bin/python3
import argparse
import logging
import re
import sys
from subprocess import run, CompletedProcess
from typing import Any

DISPLAY_RE = re.compile(r'(?P<username>[^ ]+) .*\((?P<display>:[0-9])\)')
HDMI_RE = re.compile(r'HDMI-1 connected')
VGA_RE = re.compile(r'VGA-1 connected')

_PARSER = argparse.ArgumentParser(description="Setup monitors.")
_PARSER.add_argument('-d', '--debug', action="store_true")


def _run_cmd(cmd: list[str], env: dict[str, str] | None = None, **kwargs: Any,
             ) -> CompletedProcess:
    """Run command and return result."""
    logging.debug(f"Running command: {' '.join(cmd)} env={env!r}")
    return run(cmd, env=env, **kwargs)


def is_hdmi_connected(username: str, display: str) -> bool:
    """Return whether HDMI-1 is connected."""
    xrandr_result = _run_cmd(['xrandr', '--query'], capture_output=True, check=True, encoding='utf-8',
                             env={'DISPLAY': display, 'XAUTHORITY': '/home/{}/.Xauthority'.format(username)})
    return HDMI_RE.search(xrandr_result.stdout) is not None


def is_vga_connected(username: str, display: str) -> bool:
    """Return whether VGA-1 is connected."""
    xrandr_result = _run_cmd(['xrandr', '--query'], capture_output=True, check=True, encoding='utf-8',
                             env={'DISPLAY': display, 'XAUTHORITY': '/home/{}/.Xauthority'.format(username)})
    return VGA_RE.search(xrandr_result.stdout) is not None


# Get the xrandr setup by `unxrandr` command.
HDMI_ON_CMD = [
    'xrandr',
    '--output', 'eDP-1', '--primary', '--mode', '1600x900', '--pos', '1920x0', '--rotate', 'normal',
    '--output', 'VGA-1', '--off',
    '--output', 'HDMI-1', '--mode', '1920x1080', '--pos', '0x0', '--rotate', 'normal',
    '--output', 'DP-1', '--off']
# XXX: mode 1920x1080 is sometimes not visible by xrandr :-/
# May be solved by https://askubuntu.com/a/918714
VGA_ON_CMD = [
    'xrandr',
    '--output', 'eDP-1', '--primary', '--mode', '1600x900', '--pos', '1920x0', '--rotate', 'normal',
    '--output', 'VGA-1', '--mode', '1920x1080', '--pos', '0x0', '--rotate', 'normal',
    '--output', 'HDMI-1', '--off',
    '--output', 'DP-1', '--off']
OFF_CMD = [
    'xrandr',
    '--output', 'eDP-1', '--primary', '--mode', '1600x900', '--pos', '0x0', '--rotate', 'normal',
    '--output', 'VGA-1', '--off',
    '--output', 'HDMI-1', '--off',
    '--output', 'DP-1', '--off']


def main() -> None:
    args = _PARSER.parse_args()
    if args.debug:
        level = logging.DEBUG
    else:
        level = logging.WARNING
    logging.basicConfig(stream=sys.stderr, level=level, format="%(asctime)s %(levelname)s:%(funcName)s: %(message)s")

    who_result = _run_cmd(['who'], capture_output=True, check=True, encoding='utf-8')
    for line in who_result.stdout.splitlines():
        match = DISPLAY_RE.match(line.strip())
        if not match:
            continue
        username, display = match.group('username'), match.group('display')

        # Different users see different status.
        # TODO: Resolve that xrandr returns different statuses for different users.
        if is_hdmi_connected(username, display):
            cmd = HDMI_ON_CMD
        elif is_vga_connected(username, display):
            cmd = VGA_ON_CMD
        else:
            cmd = OFF_CMD
        _run_cmd(cmd, check=True, env={'DISPLAY': display, 'XAUTHORITY': '/home/{}/.Xauthority'.format(username)})


if __name__ == '__main__':
    main()
