- name: "Add i386 architecture for steam"
  block:
    - name: "Get other available architectures"
      command: dpkg --print-foreign-architectures
      check_mode: no
      changed_when: false
      register: dpkg_arch_result
    - name: "Add i386 architecture"
      command: dpkg --add-architecture i386
      when: "'i386' not in dpkg_arch_result.stdout_lines"
      become: yes

- name: "Install nvidia drivers"
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - libgl1-nvidia-legacy-390xx-glx:i386
  when: has_nvidia

- name: "Install game packages"
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      # Minecraft deps
      - default-jre
      - libgdk-pixbuf2.0-0
      # Steam
      - steam-installer

- name: "Download minecraft.deb"
  get_url:
    url: https://launcher.mojang.com/download/Minecraft.deb
    dest: /tmp/minecraft.deb
    checksum: sha256:b8764d9bfbcbe69582aaa269469bebaddb49dda44e747b7030dd8560667ae5c8

- name: "Install minecraft"
  command: dpkg -i /tmp/minecraft.deb
  args:
    creates: /usr/bin/minecraft-launcher
  become: yes
