- name: "Add i386 architecture for steam"
  block:
    - name: "Get other available architectures"
      command: dpkg --print-foreign-architectures
      check_mode: no
      changed_when: false
      register: dpkg_arch_result
    - name: "Add i386 architecture"
      command: dpkg --add-architecture i386
      when: "'i386' not in dpkg_arch_result.stdout_lines"
      become: yes

    # Run apt update to fetch packages for i386, after it's been added.
    - name: "Run apt update"
      apt:
        update_cache: yes
      when: "'i386' not in dpkg_arch_result.stdout_lines"
      become: yes
  tags:
    - multiarch

- name: "Install nvidia drivers"
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - linux-headers-amd64  # required for DKMS to work
      - libegl-nvidia0:i386
      - libgl1-nvidia-glvnd-glx:i386
      - libglx-nvidia0:i386
      # For old NVIDIA cards:
      # - libgl1-nvidia-legacy-390xx-glx:i386
  when: has_nvidia

- name: "Install game packages"
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      # Minecraft deps
      - default-jre
      # This package needs to be installed manually. It's replaced by libgdk-pixbuf-2.0-0 and libgdk-pixbuf-xlib-2.0-0,
      # but minecraft deps are not updated.
      - libgdk-pixbuf2.0-0
      # Steam
      - steam-installer

- name: "Download minecraft.deb"
  get_url:
    url: https://launcher.mojang.com/download/Minecraft.deb
    dest: /tmp/minecraft.deb
    checksum: sha256:de839e5221b215b2c9d39ec9d9dcac9b143ed43e994e1160a31f7f81c91be9ee

- name: "Install minecraft"
  command: dpkg -i /tmp/minecraft.deb
  args:
    creates: /usr/bin/minecraft-launcher
  become: yes
