# Base system set up

- name: "Delete unused APT source file"
  file:
    dest: "/etc/apt/sources.list.d/deb_debian_org_debian.list"
    state: absent
  become: yes

- name: "Clear APT sources"
  copy:
    content: ""
    dest: /etc/apt/sources.list
  become: yes

- name: "Set up APT repositories"
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "debian"
  become: yes
  loop:
    # Debian testing sources
    # See https://wiki.debian.org/DebianTesting
    - deb https://deb.debian.org/debian testing main contrib non-free
    - deb-src https://deb.debian.org/debian testing main contrib non-free
    - deb https://deb.debian.org/debian-security/ testing-security main contrib non-free
    - deb-src https://deb.debian.org/debian-security/ testing-security main contrib non-free

- name: "Install system packages"
  apt:
    name: "{{ packages + extra_packages }}"
    state: present
  become: yes
  vars:
    packages:
      # Ansible
      # - ansible - ansible itself is not needed on nodes.
      - python3-apt
      - apt-listbugs # Warn in case there is a serious bug in the new version
      # System
      - etckeeper
      - lightdm
      - redshift
      - unattended-upgrades
      # System administration
      - bind9-dnsutils # dig, nslookup
      - deborphan
      - htop
      - resolvconf
      - rsync
      - screen
      - systemd-timesyncd # NTP client
      - tree
      # Applications
      - arandr  # GUI for video (monitors) management
      - curl
      - chromium
      - firefox-esr
      - git  # Also used by etckeeper
      - libreoffice
      - mpv
      - pavucontrol  # GUI for audio management
      - scrot # Screenshots
      - webext-ublock-origin-chromium  # uBlock Origin for chromium
      - webext-ublock-origin-firefox  # uBlock Origin for firefox
      # Vim and addons
      - vim-gtk3

- name: "Delete useless packages"
  apt:
    name: "{{ packages }}"
    state: absent
    autoremove: yes
  become: yes
  vars:
    packages:
      - aptitude
      - nano
      # Unused window managers are deleted in their roles.

- name: "Enable locales"
  locale_gen:
      name: "{{ item }}"
  become: yes
  loop:
    - en_DK.UTF-8
    - cs_CZ.UTF-8

- name: "Change default locales"
  block:
    - name: "Check default locale"
      copy:
        dest: /etc/default/locale
        content: "#  File generated by update-locale\nLANG={{ default_locale }}\nLANGUAGE={{ default_locale }}\n"
      check_mode: yes
      register: default_locale_result
    - name: "Change default locale"
      command: update-locale LANG={{ default_locale|quote }} LANGUAGE={{ default_locale|quote }}
      when: default_locale_result is changed
      become: yes
  vars:
    default_locale: en_DK.UTF-8

- name: "Set up keyboard layouts"
  copy:
    src: default_keyboard
    dest: /etc/default/keyboard
  become: yes

- name: "Disable etckeeper daily commits"
  lineinfile:
    path: /etc/etckeeper/etckeeper.conf
    regexp: "AVOID_DAILY_AUTOCOMMITS"
    line: "AVOID_DAILY_AUTOCOMMITS=1"
  become: yes

# Add delay for redshift startup, since it won't start if it's too early.
- name: "Redshift systemd override directory"
  file:
    path: "/etc/systemd/user/redshift.service.d"
    state: directory
  become: yes
- name: "Redshift systemd delay override"
  copy:
    src: "redshift.override.conf"
    dest: "/etc/systemd/user/redshift.service.d/override.conf"
  become: yes

# systemd module does not work in this case.
- name: "Enable redshift service for all users"
  command: systemctl --global enable redshift
  args:
    creates: /etc/systemd/user/default.target.wants/redshift.service
  become: yes
