# Base system set up

- name: "Delete unused APT source file"
  file:
    dest: "/etc/apt/sources.list.d/deb_debian_org_debian.list"
    state: absent

- name: "Clean up APT repositories"
  apt_repository:
    repo: "{{ item }}"
    state: absent
  loop:
    # HTTP versions
    - deb http://deb.debian.org/debian testing main contrib non-free
    - deb-src http://deb.debian.org/debian testing main contrib non-free
    - deb http://deb.debian.org/debian-security/ testing-security main contrib non-free
    - deb-src http://deb.debian.org/debian-security/ testing-security main contrib non-free

- name: "Set up APT repositories"
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "/etc/apt/sources"
  loop:
    # Debian testing sources
    # See https://wiki.debian.org/DebianTesting
    - deb https://deb.debian.org/debian testing main contrib non-free
    - deb-src https://deb.debian.org/debian testing main contrib non-free
    - deb https://deb.debian.org/debian-security/ testing-security main contrib non-free
    - deb-src https://deb.debian.org/debian-security/ testing-security main contrib non-free

- name: "Install system packages"
  apt:
    name: "{{ packages + extra_packages }}"
    state: present
  vars:
    packages:
      # Ansible itself
      - ansible
      - python3-apt
      # Warn in case there is a serious bug in the new version
      - apt-listbugs
      # System
      - etckeeper
      - i3
      - lightdm
      - redshift
      - xfce4-terminal  # Terminal emulator
      - xss-lock  # To lock screen on suspend
      - xscreensaver
      # System administration
      - bind9-dnsutils # dig, nslookup
      - deborphan
      - htop
      - ntp
      - resolvconf
      - rsync
      - screen
      - tree
      # Applications
      - arandr  # GUI for video (monitors) management
      - curl
      - docker.io # Docker
      - chromium
      - keepassxc
      - lastpass-cli # CLI for Lastpass
      - libavcodec57 # firefox-esr requires libavcodec57 to play H264 videos, see https://old.reddit.com/r/debian/comments/98chjn/firefox_esr_no_longer_supports_h264/e4jebpf/?st=jnfxvep1&sh=ec386eb1
      - libxml2-utils # xmllint
      - mpv
      - pandoc
      - pavucontrol  # GUI for audio management
      - pidgin
      - pidgin-privacy-please
      - scrot # Screenshots
      - thunderbird
      # Vim and addons
      - vim-gtk3
      - vim-addon-manager
      - vim-airline
      - vim-fugitive
      - vim-syntastic
      - vim-youcompleteme
      # Development
      - bumpversion
      - git
      - make
      # Python
      - bandit
      - ipython3
      - mypy
      - pydocstyle
      - python3-flake8
      - python3-ipdb
      - python3-isort
      - python3-pip
      - tox
      - twine
      # LuaTaX
      - texlive-luatex
      - texlive-lang-czechslovak
      - texlive-latex-extra
      # Televize dependencies
      - python3-docopt
      - python3-lxml
      - python3-m3u8

- name: "Enable locales"
  locale_gen:
      name: "{{ item }}"
  loop:
    - en_DK.UTF-8
    - cs_CZ.UTF-8

- name: "Change default locales"
  block:
    - name: "Check default locale"
      copy:
        dest: /etc/default/locale
        content: "#  File generated by update-locale\nLANG={{ default_locale }}\nLANGUAGE={{ default_locale }}\n"
      check_mode: yes
      register: default_locale_result
    - name: "Change default locale"
      command: update-locale LANG={{ default_locale|quote }} LANGUAGE={{ default_locale|quote }}
      when: default_locale_result is changed
  vars:
    default_locale: en_DK.UTF-8

- name: "Set up keyboard layouts"
  copy:
    src: default_keyboard
    dest: /etc/default/keyboard

- name: "Disable etckeeper daily commits"
  lineinfile:
    path: /etc/etckeeper/etckeeper.conf
    regexp: "AVOID_DAILY_AUTOCOMMITS"
    line: "AVOID_DAILY_AUTOCOMMITS=1"

# Add delay for redshift startup, since it won't start if it's too early.
- name: "Redshift systemd override directory"
  file:
    path: "/etc/systemd/user/redshift.service.d"
    state: directory
- name: "Redshift systemd delay override"
  copy:
    src: "redshift.override.conf"
    dest: "/etc/systemd/user/redshift.service.d/override.conf"

# systemd module does not work in this case.
- name: "Enable redshift service for all users"
  command: systemctl --global enable redshift
  args:
    creates: /etc/systemd/user/default.target.wants/redshift.service

# Based on https://askubuntu.com/a/1008029
- name: "Enable controls in xterm"
  lineinfile:
    path: /etc/X11/app-defaults/XTerm
    regexp: "\\*metaSendsEscape: .*"
    line: "*metaSendsEscape: True"
