- name: "Install i3 packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - alacritty  # Terminal emulator
      - i3
      - py3status
      - suckless-tools
      - xss-lock  # To lock screen on suspend
      - xscreensaver
  become: yes

# Set default browser
- name: "Get default browser for {{ user.name }}"
  command: xdg-settings get default-web-browser
  check_mode: no
  changed_when: false
  register: default_browser_result
  become: yes
  become_user: "{{ user.name }}"

- name: "Set default browser for {{ user.name }}"
  command: xdg-settings set default-web-browser firefox-esr.desktop
  when: "'firefox-esr.desktop' != default_browser_result.stdout"
  become: yes
  become_user: "{{ user.name }}"
