- name: "Install i3 packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - i3
      - py3status
      - suckless-tools
      - xfce4-terminal  # Terminal emulator
      - xss-lock  # To lock screen on suspend
      - xscreensaver
  become: yes

# TODO: Restart other user's i3
# - name: "Restart {{ user.name }}'s i3"
#   command: i3-msg restart --socket "{{ socket }}"
#   vars:
#     socket: "{{ lookup('fileglob', '/run/user/{}/i3/ipc-socket.*'.format(ansible_user_uid)) }}"
#   become: yes
#   become_user: "{{ user.name }}"
#   when: i3_config_result.changed

# Delete old terminal configuration
- name: "Delete {{ user.name }}'s .Xresources"
  file:
    path: "/home/{{ user.name }}/.Xresources"
    state: absent
  become: yes
  become_user: "{{ user.name }}"

# Set default browser
- name: "Get default browser for {{ user.name }}"
  command: xdg-settings get default-web-browser
  check_mode: no
  changed_when: false
  register: default_browser_result
  become: yes
  become_user: "{{ user.name }}"

- name: "Set default browser for {{ user.name }}"
  command: xdg-settings set default-web-browser firefox-esr.desktop
  when: "'firefox-esr.desktop' != default_browser_result.stdout"
  become: yes
  become_user: "{{ user.name }}"
