- name: "Set up users"
  user:
    name: "{{ user.name }}"
    # Only set password on user creation
    password: "{{ user.data.password }}"
    update_password: on_create
    state: present
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set up user groups"
  user:
    name: "{{ user.name }}"
    # Additional groups for the user
    groups: "{{ user.data.groups | default([]) }}"
    append: yes
    state: present
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Create users' $HOME/.config"
  file:
    path: "/home/{{ user.name }}/.config"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set up window manager for each user"
  include_role:
    name: "{{ window_manager | default('i3') }}"
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set czech locales"
  include_role:
    name: czech
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user
  when: user.data.czech is defined and user.data.czech

# XXX: chezmoi init hangs on prompts
# - name: "Setup dotfiles repo"
#   command: chezmoi init --no-tty https://github.com/ziima/dotfiles.git
#   args:
#     creates: "/home/{{ user.name }}/.local/share/chezmoi"
#   loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
#   loop_control:
#     loop_var: user

- name: "Setup dotfiles repo"
  git:
    repo: "https://github.com/ziima/dotfiles.git"
    dest: "/home/{{ user.name }}/.local/share/chezmoi"
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user
