- name: "Set up users"
  user:
    name: "{{ user.name }}"
    # Only set password on user creation
    password: "{{ user.data.password }}"
    update_password: on_create
    state: present
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set up user groups"
  user:
    name: "{{ user.name }}"
    # Additional groups for the user
    groups: "{{ user.data.groups | default([]) }}"
    append: yes
    state: present
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Run i3 for each user"
  include_role:
    name: "{{ window_manager | default('i3') }}"
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set up .bashrc"
  copy:
    src: bashrc
    dest: "/home/{{ user.name }}/.bashrc"
    owner: "{{ user.name }}"
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set up .vimrc"
  copy:
    src: vimrc
    dest: "/home/{{ user.name }}/.vimrc"
    owner: "{{ user.name }}"
  become: yes
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user

- name: "Set czech locales"
  include_role:
    name: czech
  loop: "{{ users | dict2items(key_name='name', value_name='data') }}"
  loop_control:
    loop_var: user
  when: user.data.czech is defined and user.data.czech
