- name: "Run i3 for each user"
  include_role:
    name: i3
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: "Set up .bashrc"
  copy:
    src: bashrc
    dest: "/home/{{ user }}/.bashrc"
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: "Set up .vimrc"
  copy:
    src: vimrc
    dest: "/home/{{ user }}/.vimrc"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
