- name: "Set up {{ user.name }}"
  user:
    name: "{{ user.name }}"
    # Only set password on user creation
    password: "{{ user.data.password }}"
    shell: "{{ user.data.shell | default('/bin/bash') }}"
    update_password: on_create
    state: present
  register: user_result
  become: yes

- name: "Set up {{ user.name }} groups"
  user:
    name: "{{ user.name }}"
    # Additional groups for the user
    groups: "{{ user.data.groups | default([]) }}"
    append: yes
    state: present
  become: yes

- name: "Set up window manager for {{ user.name }}"
  include_role:
    name: "{{ window_manager }}"

- name: "Set czech locales for {{ user.name }}"
  include_role:
    name: czech
  when: user.data.czech is defined and user.data.czech

# XXX: chezmoi init hangs on prompts
# - name: "Setup dotfiles repo"
#   command: chezmoi init --no-tty https://github.com/ziima/dotfiles.git
#   args:
#     creates: "/home/{{ user.name }}/.local/share/chezmoi"

- name: "Setup dotfiles repo"
  git:
    repo: "https://github.com/ziima/dotfiles.git"
    dest: "/home/{{ user.name }}/.local/share/chezmoi"
    update: false
  become: yes
  become_user: "{{ user.name }}"

- name: "Set up fish"
  block:
    - name: "Get fisher plugins"
      command: "fish -c 'fisher list'"
      check_mode: no
      changed_when: false
      # Ignore error if the fisher isn't installed.
      ignore_errors: true
      register: fisher_plugins
    - name: "Create fish directories"
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "/home/{{ user.name }}/.config"
        - "/home/{{ user.name }}/.config/fish"
        - "/home/{{ user.name }}/.config/fish/functions"
    - name: "Install fisher"
      get_url:
        url: https://raw.githubusercontent.com/jorgebucaran/fisher/4.4.4/functions/fisher.fish
        dest: "/home/{{ user.name }}/.config/fish/functions/fisher.fish"
        checksum: sha256:949bcff859b140808b154dfbf69aa04d99581ec8ece9747957403e33789a5864
      when: not 'jorgebucaran/fisher' in fisher_plugins.stdout.split()
    - name: "Install tide"
      command: fish -c 'fisher install "ilancosman/tide@v6"'
      when: not 'ilancosman/tide@v6' in fisher_plugins.stdout.split()
    - name: "Install z"
      command: fish -c 'fisher install "jethrokuan/z"'
      when: not 'jethrokuan/z' in fisher_plugins.stdout.split()
    - name: "Install fonts for tide"
      get_url:
        url: "https://github.com/IlanCosman/tide/blob/assets/fonts/{{ item.name }}?raw=true"
        dest: "/usr/local/share/fonts/{{ item.name }}"
        checksum: "{{ item.checksum }}"
      loop:
        - {"name": "mesloLGS_NF_regular.ttf", "checksum": "sha256:d97946186e97f8d7c0139e8983abf40a1d2d086924f2c5dbf1c29bd8f2c6e57d"}
        - {"name": "mesloLGS_NF_bold.ttf", "checksum": "sha256:b6c0199cf7c7483c8343ea020658925e6de0aeb318b89908152fcb4d19226003"}
        - {"name": "mesloLGS_NF_italic.ttf", "checksum": "sha256:6f357bcbe2597704e157a915625928bca38364a89c22a4ac36e7a116dcd392ef"}
        - {"name": "mesloLGS_NF_bold_italic.ttf", "checksum": "sha256:56b4131adecec052c4b324efb818dd326d586dbc316fc68f98f1cae2eb8d1220"}
      register: fonts_result
      become: yes
    - name: "Update font cache"
      command: fc-cache -fv
      when: fonts_result is changed
  become: yes
  become_user: "{{ user.name }}"
  when: user.data.shell | default('/bin/bash') == '/usr/bin/fish'
