- name: "Set up home computer"
  hosts: all
  roles:
    - role: system
      vars:
        extra_packages:
          # System
          - firmware-iwlwifi  # Drivers for wifi cards
          - equivs  # Simple tool to make transitional debian packages
          # Bumblebee (NVIDIA)
          - mesa-utils  # glxinfo & glxgears to check if GPU is used
          - binutils
          - bumblebee-nvidia
          - primus
          - libgl1-nvidia-legacy-390xx-glx
          - nvidia-legacy-390xx-driver
          # Utilities & applications
          - gnucash
          - keepassxc
          - nfs-common  # NFS client
          - pidgin
          - pidgin-privacy-please
          - thunderbird
          # Televize dependencies
          - python3-docopt
          - python3-lxml
          - python3-m3u8
    - role: notebook
    - role: jsignpdf
    - role: devel
    - role: users
    - role: openvpn
      when: openvpn is defined
    - role: games
    - role: printers
