- name: "Set up kosmik computer"
  hosts: all
  roles:
    - role: system
      vars:
        extra_packages:
          # System
          - firmware-iwlwifi  # Drivers for wifi cards
          - equivs  # Simple tool to make transitional debian packages
    - role: notebook
    - role: devel
    - role: users
    - role: openvpn
      when: openvpn is defined
    # - role: games
    - role: printers
