- name: "Set up puppet computers"
  hosts: puppets
  roles:
    - role: system
      become: yes
    - role: sshd
    - role: users

- name: "Puppet extra roles"
  hosts: puppets
  tasks:
    - name: "Include extra roles"
      include_role:
        name: "{{ role.name }}"
      loop: "{{ extra_roles | default([]) }}"
      loop_control:
        loop_var: role
