- name: "Create {{ item.key }} OpenVPN config directory"
  file:
    path: "/etc/openvpn/{{ item.key }}"
    state: directory
    mode: '700'
  become: yes

- name: "Copy {{ item.key }} CA"
  copy:
    src: "{{ item.value.ca }}"
    dest: "/etc/openvpn/{{ item.key }}/{{ item.value.ca }}"
    mode: '600'
  become: yes

- name: "Copy {{ item.key }} tls_auth"
  copy:
    src: "{{ item.value.tls_auth }}"
    dest: "/etc/openvpn/{{ item.key }}/{{ item.value.tls_auth }}"
    mode: '600'
  become: yes

- name: "Copy {{ item.key }} key"
  copy:
    src: "{{ item.value.key }}"
    dest: "/etc/openvpn/{{ item.key }}/{{ item.value.key }}"
    mode: '600'
  become: yes

- name: "Copy {{ item.key }} cert"
  copy:
    src: "{{ item.value.cert }}"
    dest: "/etc/openvpn/{{ item.key }}/{{ item.value.cert }}"
    mode: '600'
  become: yes

- name: "Create {{ item.key }} OpenVPN config"
  copy:
    src: "{{ item.value.config }}"
    dest: "/etc/openvpn/{{ item.key }}.conf"
    mode: '600'
  become: yes
